# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

# Note from installation instructions at wiki.rubyonrails.org:
# Rails assumes that the MySQL socket file will be found in /tmp/mysqld.sock. 
# In Debian/Ubuntu, this is not the case. Be sure to change database.yml to 
# reflect the actual location of the socket file:
# socket: '/var/run/mysqld/mysqld.sock'

development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ecoembassy_development
  pool: 5
  username: ee_user_dev
  password: jupit3r
  host: localhost
  # Note from installation instructions at wiki.rubyonrails.org:
  # Rails assumes that the MySQL socket file will be found in /tmp/mysqld.sock. 
  # In Debian/Ubuntu, this is not the case. Be sure to change database.yml to 
  # reflect the actual location of the socket file:
  socket: '/var/run/mysqld/mysqld.sock'

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ecoembassy_test
  pool: 5
  username: ee_user_dev
  password: jupit3r
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ecoembassy_production
  pool: 5
  username: ee_user
  password: demonHaunt3d
  host: localhost
